/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.richsan.bookstore

import io.richsan.bookstore.App
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
    }
}
