/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.richsan.bookstore

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.data.r2dbc.repository.config.EnableR2dbcRepositories


@SpringBootApplication
@EnableR2dbcRepositories
class App

fun main(args: Array<String>) {
    runApplication<App>(*args)
}
